### ISSUE TITLE
Adding robots.txt leads to error 404

### ISSUE THREAD

**Issue by garbast** [b13/slimphp-bridge#2]
Having the following site config, leads to an "#404 Slim\Exception\HttpNotFoundException" error 
```
routes:
  -
    prefix: /api
    groups:
      -
        routePath: /v1/de
        routes:
          -
            methods:
              - get
            routePath: /locations
            callback: 'Cp\WmdTemplate\Controller\AjaxController:filteredLocationsAction'
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
```
